spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: http://auth-server:9527
        url: http://admin-server:8101
  cloud:
    nacos:
      discovery:
        server-addr: ailuoli.cn:8848
        namespace: dev
        group: blog
    #        cluster-name: DEFAULT
    #        met
logging:
  level:
    root: info