spring:
  boot:
    admin:
      client:
        instance:
          service-url: http://127.0.0.1:9527
        url: http://ailuoli.cn:8101
  cloud:
    nacos:
      discovery:
        server-addr: ailuoli.cn:8848
        namespace: dev
        group: blog
    #        cluster-name: DEFAULT
logging:
  level:
    root: info