server:
  port: 9527
  servlet:
    context-path: /auth/server
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  profiles:
    active: dev
  rabbitmq:
    host: 182.61.43.146
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 182.61.43.146
                port: 5672
                username: admin
                password: admin
                virtual-host: my_vhost
      bindings:
        input:
          # 该参数用来设置绑定通道组，该参数主要作用于输入通道，保证同一消息组中得消息只有一个消费实例接受和处理
          # group: null
          destination: config.messages
          binder: rabbit
          content-type: application/json
          consumer:
            # 输入通道消费者得并发数
            concurrency: 1
        output:
          destination: condig.messages
          binder: rabbit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://ailuoli.cn:1234/cloud_blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cloud.blog.model
  mapper-locations: classpath*:mapper/*.xml

security:
  oauth2:
    authorization:
      jwt:
        key-alias: coding.keystore
        key-store-password: coding
        # 这里要是文件得路径 。必须要增加classpath得前缀，声明文件的地址，因为KeyStoreFactory 直接获取得，没有通过ClassPathResource.
        key-store: classpath:coding.keystore
    client:
      # 12 小时
      access-token-validity-seconds: 43200
      # 30 天
      refresh-token-validity-seconds: 604800