spring:
  profiles:
    active: dev
  application:
    name: blog-admin
  thymeleaf:
    check-template: false
    check-template-location: false
  security:
    user:
      name: coding
      password: coding
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}
      notify:
        mail:
          to: ["2665151959@qq.com"]
          from: 2665151959@qq.com

  mail:
    host: smtp.qq.com
    username: 2665151959@qq.com
    password: mpxgjlekeopkebij
    protocol: smtp
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true

server:
  port: 8101
