server:
  port: 8080
  servlet:
    context-path: /gateway/server
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: gateway-server
  rabbitmq:
    host: 182.61.43.146
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://ailuoli.cn:1234/cloud_blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: blog
    config:
      uri: http://127.0.0.1:9999
      fail-fast: true
      label: master
      username: coding
      password: coding
      retry:
        multiplier: 1.1D
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 182.61.43.146
                port: 5672
                username: admin
                password: admin
                virtual-host: my_vhost
      bindings:
        input:
          # 该参数用来设置绑定通道组，该参数主要作用于输入通道，保证同一消息组中得消息只有一个消费实例接受和处理
          # group: null
          destination: config.messages
          binder: rabbit
          content-type: application/json
          consumer:
            # 输入通道消费者得并发数
            concurrency: 1
        output:
          destination: condig.messages
          binder: rabbit
security:
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:9527/auth/server/oauth/token
      user-authorization-uri: http://127.0.0.1:9527/auth/server/oauth/authorize
      client-id: gateway-server
      client-secret: 123456
      registered-redirect-uri: http://127.0.0.1:8080/gateway/server/oauth/callback
      grant-type: authorization_code
    resource:
      token-info-uri: http://127.0.0.1:9527/auth/server/oauth/check_token
      jwk:
        key-set-uri: http://127.0.0.1:9527/auth/server/rsa/publicKey
      prefer-token-info: true
    authorization:
      check-token-access: http://127.0.0.1:9527/auth/server/oauth/check_token

feign:
  hystrix:
    enabled: true
    # 为请求和响应启动 GZIP 压缩
  compression:
    request:
      enabled: true
      # 选择压缩得类型
      mime-types: text/xml,application/xml,application/json
      # 最小请求阈值长度
      min-request-size: 2048
    response:
      enabled: true
  client:
    config:
      auth-server:
        connect-timeout: 5000
        read-timeout: 10000
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#指令命令配置，采用hystrix.command.<commandKey>作为前缀。 而<commandKey>默认情况下会采用Feign客户端的方法名作为标识。
#同样的方法名会共享Hystrix的配置，可以重写Feign.Builder的实现，并在应用主类中创建它的实例来覆盖自动化配置HystrixFeign.Builder实现
# 这里设置熔断的策略时间，因为feign 访问/oauth/token 会超时而熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cloud.blog.model
  mapper-locations: classpath:mapper/*/*.xml
logging:
  level:
    root: info
    com.cloud.gateway.service.feign: debug
#zuul:
#  add-host-header: true
#  sensitive-headers:
#  type-handlers-package: com.cloud.blog.auth.handler