spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: http://gateway-server:8080
        url: http://admin-server:8101
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: dev
        group: blog
security:
  oauth2:
    client:
      access-token-uri: http://${service.auth-server.name}/oauth/token
      user-authorization-uri: http://${service.auth-server.name}/oauth/authorize
      client-id: gateway-server
      client-secret: 123456
      registered-redirect-uri: http://${spring.application.name}/oauth/callback
      grant-type: authorization_code
    resource:
      token-info-uri: http://${service.auth-server.name}/oauth/check_token
      # 这个参数用来获取publicKey，该接口返回得是map，publicKey得键是 “value”
      jwt:
        key-uri: http://${service.auth-server.name}/oauth/token_key
    authorization:
      check-token-access: http://${service.auth-server.name}:9527/oauth/check_token
service:
  auth-server:
    host: 127.0.0.1:9527
    name: auth-server
logging:
  level:
    root: info