server:
  port: 8080
  servlet:
    context-path: /gateway/server
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  profiles:
    active: dev
  rabbitmq:
    host: 182.61.43.146
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://ailuoli.cn:1234/cloud_blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 182.61.43.146
                port: 5672
                username: admin
                password: admin
                virtual-host: my_vhost
      bindings:
        input:
          # 该参数用来设置绑定通道组，该参数主要作用于输入通道，保证同一消息组中得消息只有一个消费实例接受和处理
          # group: null
          destination: config.messages
          binder: rabbit
          content-type: application/json
          consumer:
            # 输入通道消费者得并发数
            concurrency: 1
        output:
          destination: condig.messages
          binder: rabbit
feign:
  hystrix:
    enabled: true
    # 为请求和响应启动 GZIP 压缩
  compression:
    request:
      enabled: true
      # 选择压缩得类型
      mime-types: text/xml,application/xml,application/json
      # 最小请求阈值长度
      min-request-size: 2048
    response:
      enabled: true
  client:
    config:
      auth-server:
        connect-timeout: 5000
        read-timeout: 10000
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#指令命令配置，采用hystrix.command.<commandKey>作为前缀。 而<commandKey>默认情况下会采用Feign客户端的方法名作为标识。
#同样的方法名会共享Hystrix的配置，可以重写Feign.Builder的实现，并在应用主类中创建它的实例来覆盖自动化配置HystrixFeign.Builder实现
# 这里设置熔断的策略时间，因为feign 访问/oauth/token 会超时而熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cloud.blog.model
  mapper-locations: classpath:mapper/*/*.xml
logging:
  level:
    root: info
    com.cloud.gateway.service.feign: debug
#zuul:
#  add-host-header: true
#  sensitive-headers:
#  type-handlers-package: com.cloud.blog.auth.handler




  swagger:
    enabled: true
    docket:
      base-package: io.github
