version: "3.8"
services:
  admin-server:
    image: coding1.ailuoli.cn:7777/blog-admin/blog-admin:1.0
    ports:
      - 8101:8101
    networks:
      - coding
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
networks:
  coding:
    external: true